language: node_js
language: ruby

services:
  - docker

before_install:
- ls
- docker pull node:lts
- docker run -it --rm -v $PWD:/WebVueJS -w /WebVueJS node:lts
    bash -c "cd todo; yarn install; yarn build"
script:
- bundle exec rake test