language: node_js
language: ruby

services:
  - docker

before_install:
- docker pull node:lts
- docker run -it --rm -v $PWD/pro-vuejs/todo:/todo/ -w /todo/ node:lts
    bash -c "cd todo; yarn install; yarn build"
script:
- bundle exec rake test