language: node_js
language: ruby

services:
  - docker

before_install:
- docker pull node:lts
- docker run -it --rm -v TKNgu/WebVueJS:/TKNgu/WebVueJS -w /TKNgu/WebVueJS node:lts \
    bash -c "cd todo; yarn install; yarn build"
script:
- bundle exec rake test